### ISSUE TITLE
Do we really need to remove listeners?

### ISSUE THREAD

**Issue by salmanbukharihitori** [meinto/react-native-event-listeners#8]
We are using this for token refresh. when token is refreshed an event is emitted. On IOS, we get a crash when phone is locked for a little while. Can you please advise why that is the case or is removing listeners really important?

**Comment by meinto** [comment]
Internally, the library manages a list of references. This list gets larger the more often addEventListener is called. Therefore, it is cleaner, but not mandatory, to remove the reference after use. Could you provide a stack trace please?
